services:
  - docker

cache:
  timeout: 3600
  directories:
  - ./bazel-cache

script:
  - ls -als .
  - ls -als bazel-cache
  - ls -als bazel-cache/_bazel_root
  - ./scripts/build_server_docker
  - ./scripts/build_examples_docker
  - ls -als .
  - ls -als bazel-cache
  - ls -als bazel-cache/_bazel_root
